# Generated by Django 4.0.4 on 2023-01-08 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_passengers_airports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passengers',
            name='airports',
        ),
    ]
